Vector
td2r/first-term pull request #1
Opened 2020-06-24 11:19 UTC by td2r

2020-06-24 13:44 UTC, kt-cpp requested changes
Бан по причине скат (логические/семантические ошибки при этом присуствуют, но пока что опущены)

2020-06-24 17:49 UTC, kt-cpp requested changes
Fix please

2020-06-24 17:49 UTC, kt-cpp commented on vector/vector.h
> +}
1. Лучше вызывать деструкторы в обратном порядке (т.е. как обычно)
2. Почитай, пойми что неправ, исправь
https://en.cppreference.com/w/cpp/types/is_copy_constructible
https://en.cppreference.com/w/cpp/types/is_constructible
3. Anonymous namespace in header

2020-06-24 17:49 UTC, kt-cpp commented on vector/vector.h
> +}
```erase(pos, pos +1)```

2020-06-24 17:49 UTC, kt-cpp commented on vector/vector.h
> +{
По поводу ассертов
1. Ты либо пишешь их везде (в таких функциях)
2. Либо не пишешь, и считаешь это за UB
Т.е. например front() на std::vector

Ассерты созданы для того, чтобы ты мог проверять свои собственные инварианты

2020-06-24 17:49 UTC, kt-cpp commented on vector/vector.h
> +	tmp.size_ += end() - p;
Про ассерты написано в другом сообщении, но это хороший пример

Например, если бы таких строчек было 100, то в конце хорошо бы сделать ```assert(tmp.size_ == size_ + 1)```

2020-06-24 17:49 UTC, kt-cpp commented on vector/vector.h
> +}
(про 3: хоть у нас и реализация функций в хедере, просто на будущее - не думай что можешь так писать)

2020-06-24 17:49 UTC, kt-cpp commented on vector/vector.h
> +{
Вот здесь можно добавить ```using std::swap;```

И вызвать ```swap``` вместо ```std::swap```

Тогда получишь доступ к другим возможным перегрузкам

2020-06-29 12:15 UTC, td2r commented on vector/vector.h
> +}
> (про 3: хоть у нас и реализация функций в хедере, просто на будущее - не думай что можешь так писать)

Это зарезолвленный комментарий или нет?
Просто написать sfinae на методах у меня не получилось. В шаблонных классах вовсе нельзя использовать anonymous namespace или это просто напоминание, что его нужно писать в .cpp?

2020-06-29 22:28 UTC, kt-cpp commented on vector/vector.h
> +}
Его нет смысла писать, если эти шабонные классы написаны в хедере. Потому что анонимный неймспейс в хедере - это тоже самое не писать его вообще, ибо всё из него будет видно

2020-06-30 16:46 UTC, td2r commented on vector/vector.h
> +}
>     1. Лучше вызывать деструкторы в обратном порядке (т.е. как обычно)
> 
>     2. Почитай, пойми что неправ, исправь
>        https://en.cppreference.com/w/cpp/types/is_copy_constructible
>        https://en.cppreference.com/w/cpp/types/is_constructible
> 
>     3. Anonymous namespace in header

1. Исправил
2. Исправил
3. Исправил - сделал static методами.

2020-06-30 16:47 UTC, td2r commented on vector/vector.h
> +}
> `erase(pos, pos +1)`

Fixed.

2020-06-30 16:48 UTC, td2r commented on vector/vector.h
> +{
> По поводу ассертов
> 
>     1. Ты либо пишешь их везде (в таких функциях)
> 
>     2. Либо не пишешь, и считаешь это за UB
>        Т.е. например front() на std::vector
> 
> 
> Ассерты созданы для того, чтобы ты мог проверять свои собственные инварианты

Fixed: добавил ассерты в insert и erase(first, last).

2020-06-30 16:48 UTC, td2r commented on vector/vector.h
> +	tmp.size_ += end() - p;
> Про ассерты написано в другом сообщении, но это хороший пример
> 
> Например, если бы таких строчек было 100, то в конце хорошо бы сделать `assert(tmp.size_ == size_ + 1)`

Добавил.

2020-06-30 16:48 UTC, td2r commented on vector/vector.h
> +{
> Вот здесь можно добавить `using std::swap;`
> 
> И вызвать `swap` вместо `std::swap`
> 
> Тогда получишь доступ к другим возможным перегрузкам

Fixed.

2020-06-30 17:31 UTC, kt-cpp requested changes

2020-06-30 17:31 UTC, kt-cpp commented on vector/vector.h
> +            copy_construct_all(data_, other.data_, other.size_);
[note] Ты сделал сфинае перегрузки, но при этом тут всё равно ловишь исключение. Можно конечно поверить в компилятор, который выкинет `try`, но я верю, что заморочившись можно лучше

2020-06-30 17:31 UTC, kt-cpp commented on vector/vector.h
> +        tmp.data_ = static_cast<T*>(operator new(tmp.capacity_ * sizeof(T)));
[minor] Почему бы не вызвать просто у него `reserve`?

2020-06-30 17:31 UTC, kt-cpp commented on vector/vector.h
> +}
В целом не нравится создание временного вектора и копирование абсолютно всех элементов. Хочется в отсутствии реаллокаций работать за расстояние от конца до `pos`. Подумай как это, если что можем подсказать

2020-06-30 17:31 UTC, kt-cpp commented on vector/vector.h
> +    iterator p1 = p;
1. Зачем вообще существует `p`?)
2. Понимаешь ли ты почему эти `const_cast` тут валидны?

2020-06-30 17:31 UTC, kt-cpp commented on vector/vector.h
> +size_t vector<T>::increase_capacity() const
[minor] Кажется имя это функция не соответствует содержанию. Она не увеличивает вместимость, а лишь возвращает увеличенную

2020-06-30 17:31 UTC, kt-cpp commented on vector/vector.h
> +    }
[note] А чем `for` не угодил?

2020-06-30 17:31 UTC, kt-cpp commented on vector/vector.h
> +        }
[note] Тут тоже вопрос про `for`

2020-06-30 17:31 UTC, kt-cpp commented on vector/vector.h
> +}
[note] Даже github подсказывает, что забыт перенос строки в конце файла

2020-06-30 21:02 UTC, td2r commented on vector/vector.h
> +            copy_construct_all(data_, other.data_, other.size_);
Действительно, не обратил внимания.
Сделал при помощи unique_ptr:
если copy_construct_all кидает exception, то при выходе из области видимости удалится массив
иначе просто освобождаю указатель и присваиваю в data_.

2020-06-30 21:03 UTC, td2r commented on vector/vector.h
> +        tmp.data_ = static_cast<T*>(operator new(tmp.capacity_ * sizeof(T)));
Fixed.

2020-06-30 21:04 UTC, td2r commented on vector/vector.h
> +}
Похоже я зачем-то решил повысить гарантии. Но поскольку обещаем weak, то можно переписать на end() - pos свопов, что и сделал.

2020-06-30 21:10 UTC, td2r commented on vector/vector.h
> +    iterator p1 = p;
1. Этот метод возвращает итератор на элемент, следующий за последним удаленным элементом. После всех свопов информация об этом итераторе в p1, p2 теряется, поэтому я его запоминаю и возвращаю.
2. Да, const_cast валиден, поскольку все элементы в нашем векторе не имеют идентификации const.
То есть такой код:
int const x = 2;
auto p = const_cast<int*>(&x);
*p = 3;
это undefined behaviour, поскольку x изначально создан как const и мог быть помещен в read-only секцию. Наши же объекты созданы как изменяемые.

2020-06-30 21:11 UTC, td2r commented on vector/vector.h
> +size_t vector<T>::increase_capacity() const
Поменял на increased_capacity.

2020-06-30 21:11 UTC, td2r commented on vector/vector.h
> +    }
Fixed.

2020-06-30 21:16 UTC, td2r commented on vector/vector.h
> +        }
Fixed.

2020-06-30 21:16 UTC, td2r commented on vector/vector.h
> +}
Fixed.

2020-07-01 02:40 UTC, kt-cpp commented on vector/vector.h
> +}
Если верить, что `swap` noexcept (что почти всегда правда), у элементов, то мы вполне себе получаем тут строгую гарантию, ибо её имеет `push_back`

2020-07-01 02:43 UTC, kt-cpp commented on vector/vector.h
> +            copy_construct_all(data_, other.data_, other.size_);
Интересное решение

2020-07-01 02:43 UTC, kt-cpp approved these changes

2020-07-01 02:43 UTC, merged