asm initial commit
td2r/first-term pull request #3
Opened 2020-06-29 16:29 UTC by td2r

asm initial pull request

2020-06-29 22:07 UTC, kt-cpp requested changes
Кроме косяка с памятью довольно красиво и понятно

2020-06-29 22:07 UTC, kt-cpp commented on asm/mul.asm
> +                sub             rsp, 3 * 128 * 8
Кажется ты выделил недостаточно памяти и покараптил стек

2020-06-29 22:07 UTC, kt-cpp commented on asm/mul.asm
> +                mov             [rdi], r8
Почему длина результата не превышает `rcx + 1`, и, соответственно, хватает этих действий?

2020-06-29 23:26 UTC, td2r commented on asm/mul.asm
> +                mov             [rdi], r8
Покажем, что длина произведения двух чисел не превосходит n + m (n - длина первого числа, m - второго).
Основание системы счисления b.
Если первое число - степень b, то, очевидно, длина произведения равна m + n - 1 (в начало добавится n - 1 нулей).
Иначе возьмем минимальную степень b, большую первого числа. Она будет иметь длину n + 1, а в соответствии с предыдущим предложением, произведение ее на второе число имеет длину m + n + 1 - 1 = m + n. Это произведение больше произведения данных чисел, а значит его длина не меньше искомой длины.
=> length(x * y) <= n + m
Данная функция умножает короткое число (длина 1) на длинное (длиной rcx), а значит для результата достаточно иметь rcx + 1 свободных ячеек.

2020-06-29 23:34 UTC, td2r commented on asm/mul.asm
> +                sub             rsp, 3 * 128 * 8
Я специально написал программу, которая использует 3n памяти вместо 4n.
Если нужны пояснения почему это работает, вот они:
https://ibb.co/wMJrG61
Если так делать просто нельзя, то я перепишу на 4n, хотя это было бы странно. Стек не кораптится, если считать что мы работаем с одним длинным массивом.

2020-06-30 11:31 UTC, kt-cpp commented on asm/mul.asm
> +                mov             [rdi], r8
Это конечно правда, но это про умножение, то у тебя функция возвращает выражение вида `a * b + c`, а  не просто `a * b`. Но я верю, что ты понимаешь как это доказать, так что ответ принимается

2020-06-30 11:34 UTC, kt-cpp commented on asm/mul.asm
> +                sub             rsp, 3 * 128 * 8
Я вчитался, ты прав. Прикольно, что ты так сделал, но есть два контр аргумента:
1) Вполне нормальное желание иметь в контракте функции, что она не портит свои аргументы. Однако с другой стороны тут код полностью твой и ты можешь быть к этому просто готов.
2) Это начинает уже граничить с овернинженирингом. Зачастую он приносит больше проблем чем пользы в реальности, но я не хочу никаким образом отбить у тебя желание делать крутые вещи, тем в более в контексте дз э то вполне имеет смысл. Совет на будущее - предупреждай в комментариях о таких неочевидных деталях архитектуры

2020-06-30 14:57 UTC, merged