bigint-opt initial pull request
td2r/first-term pull request #4
Opened 2020-07-04 23:08 UTC by td2r

2020-07-05 18:45 UTC, kt-cpp requested changes
* Есть глобальная проблема, потому опишу тут. Нет смысла при SO сжиматься из big в small. Дорога не сама динамическая память в ваакуме, а её выделение. Если уже выделил память, то нет смысла её понапрасну отдавать. Плюс  в случае когда у тебя часто вставляют и удаляют элементы при граничном размере у тебя буду постоянные аллокации туда сюда
* А ещё кажется имеет смысл вынести больше логики связанной с SO  в соответствующий класс с помощью статических и не очень функций

2020-07-05 18:45 UTC, kt-cpp commented on bigint-optimized/vector.h
> +    typedef uint32_t const* const_iterator;
[note] `using`...

2020-07-05 18:45 UTC, kt-cpp commented on bigint-optimized/vector.h
> +        size_t capacity;
Какие есть причины capacity не находиться рядом с данными?

2020-07-05 18:45 UTC, kt-cpp commented on bigint-optimized/vector.h
> +    static const size_t SMALL_SIZE = sizeof(buffer_data) / sizeof(uint32_t);
[note] `constexpr`

2020-07-05 18:45 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +    if (!--a->ref_counter) {
[minor] Лучше использоваться операции сравнения с интегральными данными, а не приведение к `bool`

2020-07-05 18:45 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +        buffers_.dynamic_ = alloc_data(size);
Вообще кажется нет гарантий, что динамическая память будет заполнена 0

2020-07-05 18:45 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +    memcpy(new_data.arr->words, buffers_.dynamic_.arr->words, size_ * sizeof(uint32_t));
`std::copy`

2020-07-05 21:30 UTC, td2r commented
- Да, концептуально мне бы самому хотелось так сделать. Однако я узнаю о том, маленький/большой сейчас вектор по его размеру. Размер никак не способен различить две ситуации: когда вектор всегда был маленьким, и когда он из большого стал маленьким. Из-за этого придется хранить флаг, однако тогда моя small-object оптимизация увеличит размер вектора на стеке. Я не знаю, что адекватного могу сделать в такой ситуации.
- Я пытался несколько упростить код через метод data. В resize можно сжать по два случая. Но большего я не вижу, мне нужна еще подсказка.

2020-07-05 21:31 UTC, td2r commented on bigint-optimized/vector.h
> +        size_t capacity;
Поначалу отверг этот вариант, но сейчас пересмотрел ситуацию. Если мы не боимся более длительного времени доступа к capacity, то логичнее переместить ее к массиву, чем хранить у каждого вектора. Это было единственное, что заставило меня писать так.

2020-07-05 21:31 UTC, td2r commented on bigint-optimized/vector.cpp
> +    if (!--a->ref_counter) {
Почему?

2020-07-05 21:33 UTC, td2r commented on bigint-optimized/vector.cpp
> +    memcpy(new_data.arr->words, buffers_.dynamic_.arr->words, size_ * sizeof(uint32_t));
Я использовал std::copy, чтобы активировать поле объединения. Здесь это не имеет смысла, поскольку метод вызывается, когда объект большой, а значит dynamic_ уже активирован.

2020-07-06 18:07 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +    if (!--a->ref_counter) {
Банально так проще читать + часто используется в различных гайдлайнах. Лучше выразить свою мысль более явно, от этого никому не будет хуже, а кому-то даже лучше

2020-07-06 18:09 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +    memcpy(new_data.arr->words, buffers_.dynamic_.arr->words, size_ * sizeof(uint32_t));
Несмотря на это `std::copy` в принципе более предпочтительный вариант, т.к. memcpy это наследие С, где не было понятия копирования как в плюсах. К тому же он справляется скомпилиться в столь же эффективный код, что и `memcpy` в зависимости от передаваемого типа

2020-07-06 18:13 UTC, kt-cpp commented
* В данном дз вполне можно сохранить флаг и это будет норм. В качестве хака же можно использовать старший бит `size_`, потому что `2 ^ 63 - 1` элементов в коллекции кажется хватит всем на свете
* Ну например всякие функции проверки уникальности, уменьшения и увеличения счётчика, и аллокации памяти можно туда унести

2020-07-07 02:18 UTC, td2r commented on bigint-optimized/vector.h
> +    typedef uint32_t const* const_iterator;
Fixed.

2020-07-07 02:18 UTC, td2r commented on bigint-optimized/vector.h
> +        size_t capacity;
Fixed.

2020-07-07 02:18 UTC, td2r commented on bigint-optimized/vector.h
> +    static const size_t SMALL_SIZE = sizeof(buffer_data) / sizeof(uint32_t);
Fixed.

2020-07-07 02:19 UTC, td2r commented on bigint-optimized/vector.cpp
> +    if (!--a->ref_counter) {
Fixed.

2020-07-07 02:19 UTC, td2r commented on bigint-optimized/vector.cpp
> +        buffers_.dynamic_ = alloc_data(size);
Это так. Fixed.

2020-07-07 02:19 UTC, td2r commented on bigint-optimized/vector.cpp
> +    memcpy(new_data.arr->words, buffers_.dynamic_.arr->words, size_ * sizeof(uint32_t));
Fixed.

2020-07-07 02:28 UTC, td2r commented
Постарался сделать все как сказано.
- Завел флаг small_
- Перестал сжимать вектор
- Сделал так, что метод, реаллоцирующий буффер может делать это, даже если до вызова слова хранились в статическом буффере
- Вынес немного общего кода в новую функцию.
resize, push_back и pop_back стали заметно короче.

2020-07-07 19:51 UTC, kt-cpp requested changes
В целом норм кроме твоей любви к сишных функциями вместо плюсовых

2020-07-07 19:51 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +        memset(buffers_.dynamic_->words, 0, size * sizeof(uint32_t));
[minor] `std::copy` обсуждали же до этого..

2020-07-07 19:51 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +        memset(buffers_.dynamic_->words, 0, size * sizeof(uint32_t));
Их много по коду. Найди все сам

2020-07-08 11:26 UTC, td2r commented on bigint-optimized/vector.cpp
> +        memset(buffers_.dynamic_->words, 0, size * sizeof(uint32_t));
Но это же не memcpy...
Исправил, но std::memcmp относится к стандарту C++ и std::equal был введен лишь в C++14, поэтому его оставил.

2020-09-17 18:59 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +        memset(buffers_.dynamic_->words, 0, size * sizeof(uint32_t));
Справедливо

2020-09-17 18:59 UTC, kt-cpp approved these changes

2020-09-17 18:59 UTC, merged